services:
  mysql:
    image: mysql:8.0
    container_name: add-dbms
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpass
      MYSQL_DATABASE: FiberFix
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    ports:
      - "33006:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - edu-shared

networks:
  edu-shared:
    external: true

volumes:
  mysql_data:
